// General actions
export const OPEN_DRAWER = "OPEN_DRAWER"
export const CLOSE_DRAWER = "CLOSE_DRAWER"
export const SET_DATATYPE = 'SET_DATATYPE'
export const SET_OUTPUT = 'SET_OUTPUT'
export const ALTER_ALL = 'ALTER_ALL'
export const UPDATE_ALLOW_DUPLICATE = 'UPDATE_ALLOW_DUPLICATE'
export const UPDATE_NUM_CHARS = 'UPDATE_NUM_CHARS'

// String
export const UPDATE_CHARSET = 'UPDATE_CHARSET'
export const UPDATE_DELIMITER = 'UPDATE_DELIMITER'
export const UPDATE_NUM_CASES = 'UPDATE_NUM_CASES'


// Vector
export const UPDATE_NUM_ELEMENTS = 'UPDATE_NUM_ELEMENTS'
export const UPDATE_VECTOR_ELEM_TYPE_str = 'UPDATE_VECTOR_ELEM_TYPE_str'
export const UPDATE_VECTOR_ELEM_TYPE_int = 'UPDATE_VECTOR_ELEM_TYPE_int'
export const UPDATE_VECTOR_ELEM_TYPE_float = 'UPDATE_VECTOR_ELEM_TYPE_float'
export const UPDATE_FLOAT_RANGE = 'UPDATE_FLOAT_RANGE'