export const OPEN_DRAWER = "OPEN_DRAWER"
export const CLOSE_DRAWER = "CLOSE_DRAWER"
export const UPDATE_CHARSET = 'UPDATE_CHARSET'
export const UPDATE_DELIMITER = 'UPDATE_DELIMITER'
export const UPDATE_NUM_CHARS = 'UPDATE_NUM_CHARS'